name: Test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start containers
        run: |
            cd ./integration
            docker compose up --force-recreate --build -d
      
      - name: Start client test runner
        run: docker compose run client ./client

      - name: Clean up containers
        run: docker compose down --volumes
        if: always()
